name: Tests
on: 
  push

jobs:
  sonarqube: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 18
    
    - name: Set up Gradle 7.6
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.6
    
    - name: Build and SonarCloud Scan
      run: gradle build sonarqube --info
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io

  build-and-push:
    needs: sonarqube
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker Image
      run: docker build -t nicolas10101010/backend:latest .
    
    - name: Push Docker Image
      run: docker push nicolas10101010/backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 2222
        script: |
          docker compose down --remove-orphans          
          docker compose pull          
          docker compose up -d          
          docker image prune -f
          
  wish-good-weekend:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Wishes good Weekend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 2222
        script: |
          chmod +x ./run.sh
          ./run.sh
